---
- name: Check if .ssh folder exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh"
  register: ssh_folder_stat
  become_user: "{{ ansible_env.USER }}"

- name: Create .ssh folder if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"
  when: not ssh_folder_stat.stat.exists
  become_user: "{{ ansible_env.USER }}"

- name: Check if ~/.ssh folder exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh"
  register: ssh_folder_stat

- name: Create .ssh folder if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"
  when: not ssh_folder_stat.stat.exists
  become_user: "{{ ansible_env.USER }}"

- name: Ensure ~/.ssh exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Check if id_ed25519 already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  register: id_ed25519_stat

- name: Copy and decrypt private key id_ed25519 to .ssh folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/ssh/files/id_ed25519"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    decrypt: yes
    mode: "0600"
  become_user: "{{ ansible_env.USER }}"
  when:
    - ssh_folder_stat.stat.exists
    - not id_ed25519_stat.stat.exists

- name: Check if id_ed25519.pub already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
  register: id_ed25519_pub_stat

- name: Copy public key id_ed25519.pub to .ssh folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/ssh/files/id_ed25519.pub"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
  become_user: "{{ ansible_env.USER }}"
  when:
    - ssh_folder_stat.stat.exists
    - not id_ed25519_pub_stat.stat.exists

- name: Check if seedbox already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/seedbox"
  register: seedbox_stat

- name: Copy and decrypt private key seedbox to .ssh folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/ssh/files/seedbox"
    dest: "{{ ansible_env.HOME }}/.ssh/seedbox"
    decrypt: yes
    mode: "0600"
  become_user: "{{ ansible_env.USER }}"
  when:
    - ssh_folder_stat.stat.exists
    - not seedbox_stat.stat.exists

- name: Check if seedbox.pub already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/seedbox.pub"
  register: seedbox_pub_stat

- name: Copy public key seedbox.pub to .ssh folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/ssh/files/seedbox.pub"
    dest: "{{ ansible_env.HOME }}/.ssh/seedbox.pub"
  become_user: "{{ ansible_env.USER }}"
  when:
    - ssh_folder_stat.stat.exists
    - not seedbox_pub_stat.stat.exists